sudo: false
language: python
python:
  - "2.7.11"
install: 
  - python setup.py -q install
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install -r requirements.txt
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate --noinput
  - npm install -g mocha
  - npm install jquery
  - npm install jsdom
script:
  - pep8 scout/ --exclude=migrations
  - coverage run --source=scout/ --omit=scout/migrations/* manage.py --settings=sampleproj.settings.travis test scout
  - mocha scout/static/scout/js/test --recursive
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
  slack:
        secure: QhQcPJdxvdl5GlPdiewvyMMzDAM5fFB0Db2kRwpDphn8KiyNv2cF1SVeiYaJcQ4fObA7eWgsBXGBd/be8OC/1ujGNncz92bJM5xHePzMxs37hjPFaHuDGH0pnqurQIhRTz6OoWDi2+2OzC3xP1VkpOv0/2ApFjhUkO8S6JodH9A=
